#!/usr/bin/expect -f

set username [lindex $argv 0]
set hostname [lindex $argv 1]
set password [lindex $argv 2]
set enablepwd [lindex $argv 3]
set timeout 15

# Log config
log_file -a ~/config.log
 
# Output current device and time
send_user "\n"
send_user "/***  Enable SCP on $hostname @ [exec date] ***/\n"
send_user "\n"
 
# Disable key check if needed
spawn ssh -o StrictHostKeyChecking=no $username\@$hostname
 
# Enable SSH timeout notification
expect {
    timeout { send_user "\nTimeout Exceeded > Check Device\n"; exit 1 }
    eof { send_user "\nSSH Connection To $hostname Failed\n"; exit 1 }
    "*#" {}
    "*assword:*" {
        send "$password\n"
    }
}

 
# Enter enable mode if not there
expect {
    default { send_user "\nEnable Mode Failed > Check Password\n"; exit 1 }
    "*assword:*" { send_user "\nPassword for $hostname incorrect.\n"; exit 1 }
    "*#" {}
    "*>" {
        send "enable\n"
        expect "*assword"
        send "$enablepwd\n"
        expect "*#"
    }
}

 
# Enter config mode
send "conf t\n"
expect "(config)#"
 
# Enter commands
send "ip scp server enable \n"
expect "(config)# "
send "end \n"
expect "#"
send "exit\n"
expect ":~\$"
exit 0
 

