#!/usr/bin/expect -f

set username [lindex $argv 0]
set hostname [lindex $argv 1]
set password [lindex $argv 2]
set image [lindex $argv 3]
set timeout 600

# Output current device and time
send_user "\n"
send_user "/***  Copy file to $hostname @ [exec date] ***/\n"
send_user "\n"

spawn scp   /tftp/$image $username\@$hostname:/$image

expect "*assword:"
send "$password\n"
expect "*\r"
expect "\r"
expect eof
