#!/usr/bin/expect -f

set username [lindex $argv 0]
set hostname [lindex $argv 1]
set password [lindex $argv 2]
set image [lindex $argv 3]
set timeout 300

# Log config
log_file -a ~/config.log
 
# Output current device and time
send_user "\n"
send_user "/***  Verify file on $hostname @ [exec date] ***/\n"
send_user "\n"

spawn ssh -o StrictHostKeyChecking=no $username\@$hostname

# Enable SSH timeout notification
expect {
    timeout { send_user "\nTimeout Exceeded > Check Device\n"; exit 1 }
    eof { send_user "\nSSH Connection To $hostname Failed\n"; exit 1 }
    "*#" {}
    "*assword:" {
        send "$password\n"
    }
}
 
send "verify flash:$image"

expect {
    default { send_user "\nEnable Mode Failed > Check Password\n"; exit 1 }
	"Digital signature successfully verified in file*" { send_user "Image check OK."; exit 0 }
}